DogCatWorldTeam/frontend

- abandonedpets/src/App.tsx
- abandonedpets/src/pages/SignUpPage.tsx
> design: 회원가입 페이지 퍼블리싱

- abandonedpets/src/components/funeral/FuneralList.jsx
- abandonedpets/src/components/login/LoginForm.jsx
- abandonedpets/src/components/shelter/ShelterList.jsx
- abandonedpets/src/components/signup/Register.jsx
- abandonedpets/src/pages/FuneralPage.tsx
- abandonedpets/src/pages/LoginPage.tsx
- abandonedpets/src/pages/MainPage.tsx
- abandonedpets/src/pages/ShelterPage.tsx
- abandonedpets/src/pages/SignUpPage.tsx
> refactor: 코드 구조 수정

- abandonedpets/src/App.tsx
- abandonedpets/src/components/chat/ListItem.tsx
- abandonedpets/src/components/modal/Chat.tsx
- abandonedpets/src/components/modal/ChatList.tsx
- abandonedpets/src/components/modal/FavoriteList.tsx
> [design] 채팅 리스트, 북마크 모달 퍼블리싱

- abandonedpets/src/App.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/pages/PetWrite.tsx
입양 /분양 글 작성 페이지 퍼블리싱
abandonedpets/src/App.tsx
abandonedpets/src/components/petWrite/From.tsx
abandonedpets/src/pages/PetWrite.tsx
> [design] 입양/분양 글 작성 페이지 퍼블리싱

- abandonedpets/package.json
- abandonedpets/src/components/petDetail/FavoriteBtn.tsx
- abandonedpets/src/components/petDetail/ImgList.tsx
- abandonedpets/src/components/petDetail/Info.tsx
- abandonedpets/src/components/petDetail/SendMessageBtn.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/pages/PetDetail.tsx
- abandonedpets/yarn.lock
- 상세정보 페이지
- 글 작성하기 페이지
어떤 변경 사항이 있나요?
> [design] 유기동물 상세정보 및 글쓰기 페이지 디자인 수정

- abandonedpets/.gitignore
- abandonedpets/index.html
- abandonedpets/package.json
- abandonedpets/src/components/shelter/ShelterList.tsx
- abandonedpets/src/pages/ShelterPage.tsx
- abandonedpets/tsconfig.json
- abandonedpets/yarn.lock
> [design] 보호소 페이지 디자인 수정

- abandonedpets/src/components/login/LoginForm.tsx
> design: 로그인 페이지 디자인 수정

- abandonedpets/package.json
- abandonedpets/src/components/funeral/FuneralList.tsx
- abandonedpets/yarn.lock
> design: 장례식장 페이지 디자인 수정

- abandonedpets/src/components/pets/Search.tsx
필터 내용 수정하고, mui 적용. 세부적인 디자인은 추후 수정 예정
어떤 변경 사항이 있나요?
> design: 검색 필터 내용 mui 적용

- abandonedpets/package.json
- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/signup/RegisterForm.tsx
- abandonedpets/yarn.lock
- axios 설치
- 회원가입 api 연동
회원가입에 성공하면 로그인 페이지로 이동
어떤 변경 사항이 있나요?
> feat: axios 설치 및 회원가입 api 연동

- abandonedpets/package.json
- abandonedpets/src/App.tsx
- abandonedpets/src/auth/TokenRefresher.tsx
- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/login/LoginForm.tsx
- abandonedpets/src/components/signup/RegisterForm.tsx
- abandonedpets/yarn.lock
- accessToken localStorage에 저장
- refreshToken cookie에 저장
- 로그아웃 시 localstorage 및 cookie 삭제
- 로그인 여부에 따라 navbar "로그인 회원가입" <-> "마이페이지, 로그아웃"
어떤 변경 사항이 있나요?
> [feat] 로그인 api 연동

- abandonedpets/src/App.tsx
- abandonedpets/src/components/petDetail/DetailText.tsx
- abandonedpets/src/components/petDetail/Info.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/components/pets/CatList.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/pets/PetCard.tsx
- abandonedpets/src/components/pets/SelectPage.tsx
#개
#고양이
#Detail 페이지 연동
어떤 변경 사항이 있나요?
> design: 입양/분양 페이지 api 연동

- abandonedpets/src/components/shelter/ShelterList.tsx
- abandonedpets/src/main.tsx
- 보호소 위치 지도에 마커로 찍기
해당 보호소에 대한 유기동물 데이터는 추후 추가 예정
어떤 변경 사항이 있나요?
> [feat] 보호소 전체 조회 api 연동

- abandonedpets/index.html
- abandonedpets/src/components/petDetail/DetailText.tsx
- abandonedpets/src/components/petDetail/Info.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/components/pets/CatList.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/pets/PetCard.tsx
- abandonedpets/src/components/pets/SelectPage.tsx
- abandonedpets/src/pages/Cat.tsx
- abandonedpets/src/pages/Dog.tsx
- 펫 디테일 페이지 정보 간격 벌리기
- 글 작성하기 지도 생성 및 주소 반환
어떤 변경 사항이 있나요?
> design: api 연결된 부분 세부 디자인 수정

- abandonedpets/package.json
- abandonedpets/src/components/funeral/FuneralList.tsx
- abandonedpets/src/components/mypage/FavoriteList.tsx
- abandonedpets/src/pages/FuneralPage.tsx
- abandonedpets/src/pages/Mypage.tsx
- abandonedpets/yarn.lock
> [design] 마이페이지 퍼블리싱 및 장례식장 api 연동

- abandonedpets/src/components/shelter/SelectPage.tsx
- abandonedpets/src/components/shelter/ShelterList.tsx
- 보호소 클릭 시 해당 보호소의 유기동물 데이터 연결 및 페이지네이션
이미지 흐릿한 것은 이미지 수정 중입니다
어떤 변경 사항이 있나요?
> feat: 보호소 클릭 시 유기동물 데이터 연결

- abandonedpets/src/App.css
- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/pets/PetCard.tsx
- abandonedpets/src/components/pets/Search.tsx
navbar와 dog 페이지에 반응형을 적용했습니다.
- 기본 3개
- 태블릿 환경 ( 767px < screen <= 1023px)
- 모바일 환경 (767 >= screen )
어떤 변경 사항이 있나요?
> design: navbar 및 doglist 페이지 반응형 적용

- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/login/LoginForm.tsx
- 로그인 성공 시 userId 로컬스토리지에 추가
- 로그아웃 시 userId 로컬스토리지에서 삭제
어떤 변경 사항이 있나요?
> feat: 로그인시 userId localstorage에 저장 및 삭제

- abandonedpets/src/auth/TokenRefresher.tsx
- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/login/LoginForm.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/components/pets/Search.tsx
- abandonedpets/src/pages/PetDetail.tsx
글 작성하기 api body 데이터 수정
- 보호소 이름: userId
- 보호소 전화번호: userPhone
- 보호소 주소: 보호자가 원하는 주소
어떤 변경 사항이 있나요?
> Feat: 게시글 작성 데이터 수정

- abandonedpets/src/components/petWrite/Form.tsx
fix: 백엔드로 petType 데이터 안넘어가는 것 수정
어떤 변경 사항이 있나요?
> fix: 백엔드로 petType 데이터 안넘어가는 것 수정

- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/chat/Input.tsx
- abandonedpets/src/components/chat/ListItem.tsx
- abandonedpets/src/components/chat/Messges.tsx
- abandonedpets/src/components/modal/Chat.tsx
- abandonedpets/src/components/modal/ChatList.tsx
- abandonedpets/src/components/petDetail/Info.tsx
- abandonedpets/src/components/petDetail/SendMessageBtn.tsx
- abandonedpets/src/pages/PetDetail.tsx
- 채팅방 만들기
- 대화하기
- 채팅방 삭제하기 
어떤 변경 사항이 있나요?
> feat: 채팅 기능 구현 완료

- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/funeral/FuneralList.tsx
- abandonedpets/src/components/mypage/FavoriteList.tsx
- abandonedpets/src/components/mypage/MyPageList.tsx
- abandonedpets/src/pages/Mypage.tsx
> [Design] 마이페이지 api연동 및 디자인 수정

- abandonedpets/src/components/petWrite/Form.tsx
fix: 펫 게시글 작성할때 userId 추가
어떤 변경 사항이 있나요?
> fix: 펫 게시글 작성할때 userId 추가

- abandonedpets/src/App.tsx
- abandonedpets/src/auth/TokenRefresher.tsx
- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/chat/InfoBar.tsx
- abandonedpets/src/components/chat/Input.tsx
- abandonedpets/src/components/chat/ListItem.tsx
- abandonedpets/src/components/chat/Messges.tsx
- abandonedpets/src/components/funeral/FuneralList.tsx
- abandonedpets/src/components/modal/Chat.tsx
- abandonedpets/src/components/modal/ChatList.tsx
- abandonedpets/src/components/mypage/FavoriteList.tsx
- abandonedpets/src/components/mypage/MyPageList.tsx
- abandonedpets/src/components/petDetail/DetailText.tsx
- abandonedpets/src/components/petDetail/Info.tsx
- abandonedpets/src/components/petDetail/SendMessageBtn.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/components/pets/CatList.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/pets/PetCard.tsx
- abandonedpets/src/components/shelter/ShelterList.tsx
- abandonedpets/src/main.tsx
- abandonedpets/src/pages/LoginPage.tsx
- abandonedpets/src/pages/PetDetail.tsx
- abandonedpets/src/pages/ShelterPage.tsx
- abandonedpets/src/pages/SignUpPage.tsx
- dog board 및 detail page 디자인 수정
- dog board list 북마크 추가 및 삭제 기능 추가
- yarn build 에러 해결
어떤 변경 사항이 있나요?
> fix: yarn build

- abandonedpets/.gitignore
- abandonedpets/src/components/funeral/FuneralList.tsx
- abandonedpets/src/components/login/LoginForm.tsx
- abandonedpets/src/components/mypage/MyPageList.tsx
- abandonedpets/src/components/petDetail/Info.tsx
- abandonedpets/src/components/petDetail/SendMessageBtn.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/components/pets/CatList.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/pets/PetCard.tsx
- abandonedpets/src/components/pets/Search.tsx
- abandonedpets/src/components/shelter/ShelterList.tsx
- abandonedpets/src/components/signup/RegisterForm.tsx
- abandonedpets/src/pages/Cat.tsx
- abandonedpets/src/pages/Dog.tsx
- abandonedpets/src/pages/FuneralPage.tsx
- abandonedpets/src/pages/PetDetail.tsx
- abandonedpets/src/vite-env.d.ts
1. 강아지 및 고양이 페이지에서 검색 api 연동
2. petDetail 페이지에서 입양 상태값 백엔드 데이터와 연동
3. 개발용과 배포용 URL 설정 및 수정
어떤 변경 사항이 있나요?
> [feat] 검색 api 연동

- abandonedpets/src/components/mypage/MyPageList.tsx
> design: 마이페이지 내가 쓴 글 삭제 연동

- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/modal/Chat.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/pets/PetCard.tsx
> fix: 콘솔 경고 메세지 오류 수정

- abandonedpets/Dockerfile
- abandonedpets/src/auth/TokenRefresher.tsx
- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/chat/Messges.tsx
- abandonedpets/src/components/modal/Chat.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/components/pets/CatList.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/pets/Search.tsx
- abandonedpets/vite.config.ts
- access 토큰 값 넣어주는 것 했지만, 아직 제대로 동작하지 않음
- kakao map key 재발급
- dockerfile 수정
- 실시간 채팅 구현 완료 
- 글 작성 이후 dog board 페이지로 이동
- 마이페이지/로그아웃 접근성 개선 (위치 조정)
어떤 변경 사항이 있나요?
> [fix] 에러 및 디자인 개선

- abandonedpets/src/App.tsx
- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/mypage/MyPageList.tsx
- abandonedpets/src/components/petDetail/FavoriteBtn.tsx
- abandonedpets/src/components/petDetail/Info.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/components/pets/CatList.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/pets/PetCard.tsx
- abandonedpets/src/components/signup/RegisterForm.tsx
- abandonedpets/src/pages/PetDetail.tsx
- 글 작성시 이미지만 올라가는 문제 있어서 해결 필요
- 북마크 post 성공해도 북마크 여부 false로 나타나는 문제 해결 필요
- yarn build 오류 해결
어떤 변경 사항이 있나요?
> [fix] 글 작성, 북마크 api 연동 및 yarn build 오류 해결

- abandonedpets/src/pages/PetDetail.tsx
- 유저 북마크 여부에 따른 true/false 반영
어떤 변경 사항이 있나요?
> fix: 북마크 api url 오류 해결

- abandonedpets/src/components/signup/RegisterForm.tsx
> design: password placeholder 설명 추가

- abandonedpets/src/components/petDetail/ImgList.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/pets/PetCard.tsx
- abandonedpets/src/components/pets/Search.tsx
- abandonedpets/src/pages/PetDetail.tsx
글 작성 api 연동 및 추가 이미지들 불러오기 완료
어떤 변경 사항이 있나요?
> [fix] 글 작성 api 연동 완료 및 yarn build 오류 수정

- abandonedpets/src/components/chat/Input.tsx
- abandonedpets/src/components/modal/Chat.tsx
- abandonedpets/src/components/petDetail/FavoriteBtn.tsx
- abandonedpets/src/components/pets/Search.tsx
- 북마크 카운트 즉시 반영
- search placeholder 변경
어떤 변경 사항이 있나요?
> [fix] 북마크 숫자 카운트 개선

- abandonedpets/src/components/NavBar.tsx
- abandonedpets/src/components/modal/Chat.tsx
- abandonedpets/src/components/modal/ChatList.tsx
- abandonedpets/src/components/petDetail/SendMessageBtn.tsx
- 채팅 관련 api를 로컬에서 배포에도 적용되도록 수정
- stmop url 설정
어떤 변경 사항이 있나요?
> [fix] 채팅 api 배포 연결 설정

- abandonedpets/src/components/modal/Chat.tsx
- abandonedpets/src/components/petDetail/SendMessageBtn.tsx
- 채팅 socket url 설정 오류 수정
어떤 변경 사항이 있나요?
> fix: 채팅 socket url 수정

- abandonedpets/index.html
- abandonedpets/src/App.css
- mixed content 에러 수정
어떤 변경 사항이 있나요?
> fix: 배포 http 오류 수정

- abandonedpets/src/components/chat/ListItem.tsx
- abandonedpets/src/components/funeral/FuneralList.tsx
- abandonedpets/src/components/modal/Chat.tsx
- abandonedpets/src/components/modal/ChatList.tsx
- abandonedpets/src/components/mypage/MyPageList.tsx
- abandonedpets/src/components/petDetail/FavoriteBtn.tsx
- abandonedpets/src/components/petWrite/Form.tsx
- abandonedpets/src/components/pets/CatList.tsx
- abandonedpets/src/components/pets/DogList.tsx
- abandonedpets/src/components/shelter/ShelterList.tsx
- abandonedpets/src/pages/PetDetail.tsx
- api 각각의 헤더에 access token 추가
어떤 변경 사항이 있나요?
> fix: add api header access token

- abandonedpets/src/components/pets/PetCard.tsx
- abandonedpets/src/components/pets/Search.tsx
- 검색 나이 입력 안 했을 시 오류 발생 취소
- petlist card [품종] 추가 및 제목 수정
어떤 변경 사항이 있나요?
> [fix] 검색 및 petlist card 제목 수정

- abandonedpets/src/components/pets/PetCard.tsx
- abandonedpets/src/components/pets/Search.tsx
> [fix] 검색 오류 수정 및 petlist card 제목 수정

- src/components/NavBar.tsx
- src/components/shelter/ShelterList.tsx
- shelter 페이지
favorite btn 없어도 돼서 삭제
품종 안 나타나서 response data 보고 수정완료
- navbar 컴포넌트
chat import 경로 간략화 수정
어떤 변경 사항이 있나요?
> design: shelter petlist favorite btn delete, 품종, navbar chat 경로 수정

- src/components/funeral/FuneralList.tsx
- src/vite-env.d.ts
장례식장 페이지 api 오류 수정 
어떤 변경 사항이 있나요?
> fix: 장례식장 페이지 api 오류 수정

- src/components/chat/ListItem.tsx
- src/components/modal/Chat.tsx
- src/components/petDetail/SendMessageBtn.tsx
채팅 엔드포인트를 수정했습니다.
어떤 변경 사항이 있나요?
> fix: 채팅 엔드포인트 수정

- src/components/chat/ListItem.tsx
- src/components/modal/Chat.tsx
- src/components/petDetail/SendMessageBtn.tsx
- src/components/signup/RegisterForm.tsx
- socket 엔드포인트 url에 맞게 수정
- 회원가입 실패 alert message 설정
어떤 변경 사항이 있나요?
> fix: socket 채팅 엔드포인트 설정 및 회원가입 실패 alert 설정

- src/components/funeral/FuneralList.tsx
- src/components/signup/RegisterForm.tsx
- 장례식장 페이지 baseurl 사용해서 수정
- 회원가입 비밀번호 입력 alert 메세지 처리
어떤 변경 사항이 있나요?
> fix: 장례식장 페이지 api 수정 및 회원가입 비밀번호 입력 에러처리

- src/components/chat/ListItem.tsx
- src/components/modal/Chat.tsx
- src/components/petDetail/SendMessageBtn.tsx
> fix: socket 엔드포인트 수정
